//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaChorizadaDeCata
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int id_detalle { get; set; }
        public Nullable<int> factura { get; set; }
        public Nullable<int> producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual Factura Factura1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
